= Project Icarus

A new age of power has been developed by the Refined R&D department, allowing heat from concentrated sun rays to boil water into a highly compressed steam.

The program was terminated because the Ficsit engineers had to come down to MASSAGE-2(A-B)b and fix the Dyson Sphere.

== Introduction

[NOTE]
====
Project Icarus is end-game content.
====

As the Dyson Sphere Program was one of the first staple massive buildings in Refined Power, it was introduced to the game around Update2 / Update3.

The project didn't have any ability to use some of the new features that the game offered in those updates, e.g. pipes and space elevator parts.

Due to the number of issues encountered with Dyson Sphere, the Refined R&D Team decided it was not worth updating and started a new Project called Icarus.

Icarus has many similar traits to the Dyson Sphere but with an elevated feel.

== Getting Started

Getting started with Icarus requires you to have unlocked Tier 7/8 in the game.

Repair kits will need to be sent into space to keep the Icarus Ray deflector in space in working order.

You can send the different Repair kits to the deflector in space using an Icarus Rail Gun.


=== Icarus Receiver
It will become active once the Ray deflector has enough repair kits and is green in the Icarus Reciever UI.

Once activated, Water can be piped into the building and converted to Compressed Steam.
Compressed Steam can then be piped to the Super HV Turbines.

The building only works in the daytime and will go into standby mode at night.
It is advised that power storage is used to handle the nighttime period.

=== Icarus Rail Gun

The Rail Gun will charge up with power, and once at max stored power, it will be released in a surge of energy to shoot the items into space.

=== Repair Kits

There are four variants of Repair kits, and they all have different recipes.

* Icarus Basic Repair Kit
* Icarus Pioneer Repair Kit
* Icarus Reinforced Repair Kit
* Icarus Electrical Repair Kit