= Farming Modules


Modules add additional Features to the Plot.
Farming Modules can be placed after any plot is placed, but not every plot accepts every module.
Additionally, some seeds need a specific module to be able to grow.

== Harvester Module
Like the name says already, this module harvests a full plot.
The harvested item will be moved to the Platform Storage.

[TIP]
====
Can be placed on every plot.
====

** Power Usage: 10 MW
** 20x Cable
** 4x Motor
** 20x Modular Frame
** 25x Encased Industrial Beam

== Irrigation Module
Sprays given fluid to the seeds.

* Mycelia Seeds need this module to grow.
* Any Enriched or Fertilized Seed need this module to grow.

[TIP]
====
Can be placed on every plot.
====

** Power Usage: 5 MW
** 25x Copper Sheet
** 15x Steel Pipe
** 10x Cable

== Greenhouse Module
Provides better growing conditions for more efficient farms.
In other words, it reduces the time between production ticks.

* Mycelia seeds need this module to grow.

[TIP]
====
Can be placed on every plot **except tree plots**
====

** Power Usage: 5 MW
** 50x Iron Plate
** 12x Modular Frame
** 30x Silica
