= Farming Modules

Farming Modules can be placed after any Plot is placed but not every Plot accept every Module.
Modules add additional Features to the Plot.
Also some Seeds or Seeds Version need a specific Module to be able to grow.

== Harvester Module
Like the Name says already this Module harvest a full Plot.
The harvested item will be moved to the Platform Storage.

[TIP]
====
Can be placed on every Plot
====

** Power Usage: 12 MW
** 20x Cable
** 4x Motor
** 20x Modular Frame
** 16x Encased Industrial Beam

== Irrigation Modue
Sprays given Fluid to the Seed
* Mycelia Seed need this Module to grow
* Any Enriched or Fertilized Seed need this Module to grow

[TIP]
====
Can be placed on every Plot
====

** Power Usage: 2 MW
** 16x Copper Sheet
** 8x Steel Pipe

== Greenhouse Module
Provides better Habitat Conditions and speed up growing.
So in other Word it reduces the Time between Production Ticks.
* Mycelia Seed need this Module to grow

[TIP]
====
Can be placed on every Plot except Tree Plots
====

** Power Usage: 30 MW
** 50x Iron Plate
** 12x Modular Frame