= Additional Buildings

## Seed Extractor

[WARNING]
====
This Building is outdated! we reworked how it works.
====

The Seed Extractor can convert Jar of Dirt or a Crop into Seeds.
Important on this Step is that you gain multiple Seeds OR a higher Count of Seed from an Item.
A conversion list can be viewed in the Seed Extractor Menu of the Building.

* Power Usage: 25 MW
* Conveyor Input: 1
* Conveyor Output: 1
* Fluid Input: 0
* Fluid Output: 0
* Space in Foundations : 1x2 (rounded)
* Build Cost:
** 20x Modular Frame
** 18x Rotor
** 25x Cable

## Doggo House
Doggos need Water and Food. In return, you get some random items back from what they found.
To collect Doggos for the House you need to pet them, then pick them up with an Empty Cage.

* Power Usage: 16 MW
* Conveyor Input: 2
* Conveyor Output: 1
* Fluid Input: 1
* Fluid Output: 0
* Space in Foundations (rounded) : 7x4
* Build Cost:
** 16x Modular Frame
** 20x Concrete
** 15x Jar of Dirt

## Cooking Hub
Convert crops into edible things. Surprisingly, it cooks things :-P
In general it takes crops and water for this process

* Power Usage: 28 MW
* Conveyor Input: 2
* Conveyor Output: 1
* Fluid Input: 1
* Fluid Output: 1
* Space in Foundations (Rounded): 2x2
* Build Cost:
** 20x Steel Beam
** 20x Cable
** 12x Encased Industrial Beam

## Composter

Converts all Organic material plus water into Fertilizer.

Fertiliser can be used in the Plots or converted to Biomass in a Refinery

* Power Usage: 10 MW
* Conveyor Input: 1
* Conveyor Output: 0
* Fluid Input: 1
* Fluid Output: 1
* Space in Foundations (Rounded): 1x3
* Build Cost:
** 12x Modular Frame
** 20x Cable
** 12x Rotor
