= Change Logs

## Ficsit Farming Change Log v3.0.2

* Multiplayer support - Multiplayer now works fully tm for this mod
* Items are now returned to the inventory if possible when switching recipies
* Mycelia and flowers now produce their correct seeds when put into the seed extractor

Thank you to all of our patreons and the rest of the community for finding bugs. If you find any more, please make sure you report them so we can get them fixed as quick as possible

If you have more questions you want to ask please join our discord and chat with us and the rest of the community!

## Ficsit Farming Change Log v3.0.1

* Fixed doggo house indicators
* Fixed doggo cage recipe
* Fixed yosse muffin name
* Updated milestones and related messages
* Fixed seed naming
* Optimised farming platform for more liquid intake
* Updated dirt node

Thank you to all of our patreons and the rest of the community for finding bugs. If you find any more, please make sure you report them so we can get them fixed as quick as possible

If you have more questions you want to ask please join our discord and chat with us and the rest of the community!