= How to Farming - The Basics

To start your farming career, you need to follow a few steps.

== Unlock the Equipment
Head up to the HUB and you will find several new Milestones.
Unlock the *_Basic Farmer - Buildings_* Milestone in Tier 2.

== Locate and Dig up Jars of Dirt
Like any resource node, you need to use the Resource Scanner to find the *_Jar of Dirt_* nodes.
A Portable Miner can auto-collect this for you.

== Begin Seed Automation
You can place a Miner on the node. Node purity dictates the output per minute. 
A Normal purity node outputs 60 Jars of Dirt per minute from a Mk.1 Miner.
Each Seed Extractor can process 30 jars per minute and produce 20 Wheat Seeds, 20 Carrot Seeds, 10 Corn
Seeds, and 10 Potato Seeds per minute (60 seeds total per minute). Send
the seeds either to Storage Containers or directly to a Farm. 
Use Smart or Programmable splitters to organize the seeds.

[NOTE]
====
Different dirt types produce different seeds.
====

== Build Your First Farm
Unlock the *_Basic Farmer - Crops_* Milestone in Tier 2 to be able to select crops later.

Build a *_Farming Platform Mk1_* first. Place a *_Crop Plot_* onto the Platform.

Opening the Platform's menu allows you to see its internal storage. 
Opening the Plot's menu allows you to choose a Crop to grow and see its growth progress.

Go to the Plot and select the crop you want to produce.
Connect the Platform to your power grid to start the growing process.

== Collect Your First Crops
You can manually collect your crops as soon as a cycle completes. Remember to grab the Biomass Capsules too. Congratulations!

== Crop Automation
At this point you may start wondering why the crops aren't leaving the Plot.

To have this happen, you need to unlock the *_Harvester Module_* under the *_Apprentice Farmer - Buildings_* Milestone in Tier 3.
Placing it on the Plot will start moving crops to the Platform's internal storage. If there is a belt connected, the crops will exit onto the belt.

You can unlock more crops and improve crop yield by unlocking more farming equipment in the HUB.

Now you know the basics about farming.

== How to Doggo - The Basics
You like Doggos and want to have them around you all the time, but also keep them safe? Perfect!

You need all the Ficsit Farming milestones up to Tier 5. 
In Tier 6, you first unlock *_Peat Soil_* to unlock apples. Farm enough apples to unlock the *_Rancher_* Milestone.

Before collecting Lizard Doggos, build the *_Doggo House_* and provide Power, *_Doggo Chow_*, and Water.
Doggo Chow is made in the *_Cooker_* with *_Yosse Berries_* and Mycelia. One Doggo eats 0.5 Doggo Chow per minute and drinks about 28m^3^ Water/min.
[WARNING]
====
Be sure that the house is all set up *BEFORE* you put Lizard Doggos inside or they will start losing health!
====

Craft a *_Doggo Cage_* in the Equipment Workshop. Find a Doggo and left click them with the Empty Cage to carry them with you. You do not have to rush back, they can be held indefinitely in the cage. Once back, drag the Full Cage into the UI of the Doggo House, on the left, and click the *_Deposit Doggo_* button. Just to be sure, also click the *_Befriend All Doggos_* button. You will get the Empty Cage back in the other side of the UI or it will be put on the conveyer exiting from the Doggo House.

[NOTE]
====
If you need to remove Doggos from Doggo House, currently the only option is to dismantle the house. Be sure you have befriended all the Doggos before you dismantle and they will stay befriended. 
====

[WARNING]
====
Doggos will *not* stay befriended if they are picked up in the cage and released onto the ground.
====
