= Modular Power Chimneys

== Information:
Modular Power Chimneys are used to vent CO₂ and Steam from heaters and turbines. They have to be placed on a Cooling Platform

== Building Information:

|===
| |Co2 Chimney |Steam Cooling Tower
|Building Cost
|20x Copper Sheet +
4x Reinforced Iron Plate +
2x Carbon Mesh
|20x Copper Sheet +
4x Reinforced Iron Plate +
2x Carbon Mesh

|Fluid
|Co2
|Low Pressure Steam

|Consumption rate
|150 m³
|300 m³


|===

== Milestones

|===
| |Co2 Chimney |Steam Cooling Tower

|Available with
|Tier 3
|Tier 3

|Research Cost*
|25x Reinforced Iron Plate +
25x Rotor +
200x Iron Rod +
500x Cable
|25x Reinforced Iron Plate +
25x Rotor +
200x Iron Rod +
500x Cable
|===

*{sp}Both buildings are in the same milestone. Within the milestone, multiple Refined Power buildings are unlocked.

[NOTE]
====
you can also reuse the steam by refining it back into water if you replace the steam chimney with a refinery with the steam recipe, you can set the clock so you get an exact water in/out ratio of 1:1
Although this does consume more power and space it allows you to create a closed loop water/steam system for use when you are far away from a water source
====