= Modular Power Heaters

## Building Information:
Heaters are used to burn fuel to make heat. Currently there are 4 variants: Biomass, Coal, Solution & Nuclear.

Once the heater reaches 100℃ the attached Boiler will then start producing Steam, the temperature will reach 1050℃ for the nuclear heater. 750c for the solution heater and 500℃ for the rest.

The heater will produce CO₂, which will need to be handled by either venting through a chimney or accumulating into Carbon Dust. If the Co2 is not resolved and fills the heater, it will stop producing heat and slowly cool.

## Variants:

### Biomass Heater
The biomass heater can produce 500℃ heat and can be fed with the following items:

|===
| Item   | Heat / Cycle | Consumption / Min | CO₂  / Min
| Leaves|0.5|120|12.0 m³
| Wood|1|30|6.0 m³
| Mycelia|2|60|12.0 m³
| Alien Carapace|10|10|2.4 m³
| Fabric|5|60|6.0 m³
| Alien Organs|10|10|2.4 m³
| Biomass|20|25|4.8 m³
| Solid Biofuel|30|10|10.0 m³
| Packaged Biofuel|35|4|5.0 m³
| Flower|0.25|60|9.0 m³
|===

### Coal Heater
The coal heater can produce 500℃ heat and can be fed with the following items:

|===
| Item   | Heat / Cycle | Consumption / Min |  CO₂  / Min
|Coal|10|15|7.5 m³
|Petrolium Coke|6|25|3.6 m³
|Compacted Coal|15|6|7.5 m³
|===

### Solution Heater
The Solution heater can produce 750℃ heat and can be fed with the following items:
|===
| Item   | Heat / Cycle | Consumption / Min | CO₂  / Min
| Biofuel|25|20 m³|24.0 m³
| Fuel|30|25 m³|16.0 m³
| Turbofuel|35|8 m³|30.0 m³
|===

### Nuclear Heater
The Nuclear heater can produce 1050℃ heat and can be fed with the following items:

|===
| Item   | Heat / Cycle | Consumption / Min | Waste | Waste  / Min
| Nuclear Fuel Rods|1050|0.133|Nuc Waste (Vanilla)| 3.333
| Plutonium|1050|0.067|Plutonium Waste (Vanilla)| 0.333
| Advanced Reactor Cores|1050|0.133|Advanced Reactor Casing| 0.133
|===
