= Modular Power Heaters

## Building Information:
Heaters are used to burn fuel to make heat, currently there is 4 variants of heaters. Biomass, Coal, Solution & Nuclear.

Once the heater reaches 100c the attached Boiler will then start producing Steam, the temperature will reach 1024c for the nuclear heater and 500c for the rest.

The heater will produce Co2 which will need to be handled wither by venting through a chimney or turned into Carbon Dust, if the Co2 is not resolved and fills the heater, it will stop producing heat and slowly cool.

## Variants:

### Biomass Heater
The biomass heater can produce 500c heat and can be fed with the following items:

|===
| Item   | Heat / Cycle | Consumption / Min
| Leaves|0.5|120
| Wood|1|30
| Mycelia|2|60
| Carapace|10|10
| Fabric|5|60
| Organs|10|10
| Biomass|20|25
| BioFuel|30|10
| PackagedBioFuel|35|4
| Flower|0.25|60
|===

### Coal Heater
The coal heater can produce 500c heat and can be fed with the following items:

|===
| Item   | Heat / Cycle | Consumption / Min
|Coal|10|15
|Petrolium Coke|6|25
|Compacted Coal|15|6
|===

### Solution Heater
The Solution heater can produce 500c heat and can be fed with the following items:
|===
| Item   | Heat / Cycle | Consumption / Min
| Bio Fuel|25|20
| Fuel|30|25
| Turbo Fuel|35|8
|===

### Nuclear Heater
The Nuclear heater can produce 1024c heat and can be fed with the following items:

|===
| Item   | Heat / Cycle | Consumption / Min | Waste
| Nuclear Fuel Rods|1200|0.4|Nuc Waste (Vanilla)
| Plutonium|3000|0.4|Plutonium Waste (Vanilla)
| Advanced Reactor Cores|2500|0.2|Advanced Reactor Casing
|===
