= Modular Power Heaters

## Building Information:
Heaters are used to burn fuel to make heat, currently there is 4 variants of heaters. Biomass, Coal, Solution & Nuclear.

Once the heater reaches 100c the attached Boiler will then start producing Steam, the temperature will reach 1050c for the nuclear heater. 750c for the solution heater and 500c for the rest.

The heater will produce Co2 which will need to be handled wither by venting through a chimney or turned into Carbon Dust, if the Co2 is not resolved and fills the heater, it will stop producing heat and slowly cool.

## Variants:

### Biomass Heater
The biomass heater can produce 500c heat and can be fed with the following items:

|===
| Item   | Heat / Cycle | Consumption / Min | Waste | Waste  / Min
| Leaves|0.5|120|Co²|12 m³
| Wood|1|30|Co²|6 m³
| Mycelia|2|60|Co²|12 m³
| Carapace|10|10|Co²|2,4 m³
| Fabric|5|60|Co²|6 m³
| Organs|10|10|Co²|2,4 m³
| Biomass|20|25|Co²|4,8 m³
| BioFuel|30|10|Co²|10 m³
| PackagedBioFuel|35|4|Co²|5 m³
| Flower|0.25|60|Co²|9 m³
|===

### Coal Heater
The coal heater can produce 500c heat and can be fed with the following items:

|===
| Item   | Heat / Cycle | Consumption / Min | Waste | Waste  / Min
|Coal|10|15|Co²|7,5 m³
|Petrolium Coke|6|25|Co²|3,6 m³
|Compacted Coal|15|6|Co²|7,5 m³
|===

### Solution Heater
The Solution heater can produce 750c heat and can be fed with the following items:
|===
| Item   | Heat / Cycle | Consumption / Min | Waste | Waste  / Min
| Bio Fuel|25|20 m³|Co²|24 m³
| Fuel|30|25 m³|Co²|16 m³
| Turbo Fuel|35|8 m³|Co²|37,54 m³
|===

### Nuclear Heater
The Nuclear heater can produce 1050c heat and can be fed with the following items:

|===
| Item   | Heat / Cycle | Consumption / Min | Waste | Waste  / Min
| Nuclear Fuel Rods|1200|0.4|Nuc Waste (Vanilla)| 10
| Plutonium|3000|0.2|Plutonium Waste (Vanilla)| 1
| Advanced Reactor Cores|2500|0.4|Advanced Reactor Casing| 0.4
|===
