= Modular Power Turbines

== Information:
Modular Power Turbines use High Pressure Steam to produce RPM and convert it to Low Pressure Steam in the process.

RPM is used with the attached Generators you can lower or raise the RPM by discarding any steam and sending it directly out the output connection.

The Low Pressure Steam must be piped out the turbines into a Steam cooling tower or used to create water. If the low pressure steam is not removed from the turbine the RPM will slowly decrease and eventually stop.

They have to be placed on Converter Platforms.

== Building Information

|===
| |Mk. 1 |Mk. 2 |Super HV 

|Building Cost
|20x Reinforced Iron Plate +
6x Modular Frame +
10x Rotor
|6x Heavy Modular Frame +
10x Motor +
4x Computer
|

|Maximum RPM
|10 000
|25 000
|

|Steam Consumption +
(High Pressure)
|60 m³
|120 m³
|300 m³ (Compressed Steam)


|Steam Production +
(Low Pressure)
|60 m³
|120 m³
|450 m³

|===

== Milestones

|===
| |Mk. 1 |Mk. 2 |Super HV 

|Available with
|Tier 3
|Tier 5
|Tier 7

|Research Cost*
|25x Reinforced Iron Plate +
25x Rotor +
200x Iron Rod +
500x Cable
|100x Plastic +
50x Rubber +
500x Copper Sheets
|
|===

*{sp}Within the milestones, multiple Refined Power buildings are unlocked.