= Modular Reactor Modes

== Modes
There are 3 possible modes for the Reactor to operate in.
In all modes there is a *spin up time* starting the reactor and changing the reactor clock setting

Overclocking the Reactor above 100% (or 150% with coolant) will result in the reactor gaining heat , reaching the max temperature will cause the reactor to trigger an emergency shutdown
Underclocking the reactor will cause it to loose heat.

[NOTE]
====
You can see the current Reactor Heat in the Reactor Foundation screen, you can see the heat per cycle in the IO Modules screen
====

== Stats

These stats are with shielding MK. 3 rings and Reactor Cooling rings with coolant

=== Power only
In power only mode the reactor will only output power to the power grid

====Reactor Stats

===== DT Reactor Cores

|===
| |Power(MW)|Fuel/min |Water |coolant |Heat Gain 

|Clock @ 25%
|1,250
|0.25
|3
|3
|16.7%

|Clock @ 50%
|2,500
|0.5
|3
|3
|33.3%

|Clock @ 50%
|2,500
|0.75
|3
|3
|50%

|Clock @ 100%
|5,000
|1
|3
|3
|66.7%

|Clock @ 150%
|7,500
|1.5
|3
|3
|100%

|Clock @ 200%
|10,000
|2
|Increases as temperature rises up to 240
|Increases as temperature rises up to 60
|133.3%

|Clock @ 250%
|10,000
|2.5
|Increases as temperature rises up to 240
|Increases as temperature rises up to 60
|166.7%
|===

===== Deanorium Reactor Cores        
|===
| |Power(MW)|Fuel/min |Water |coolant |Heat Gain

|Clock @ 25%
|1,250
|0.063
|2
|2
|16.7%

|Clock @ 50%
|2,500
|0.125
|2
|2
|33.3%

|Clock @ 100%
|5,000
|0.25
|2
|2
|66.7%

|Clock @ 150%
|7,500
|0.375
|2
|2
|100%

|Clock @ 200%
|10,000
|0.5
|Increases as temperature rises up to 240
|Increases as temperature rises up to 60
|133.3%

|Clock @ 250%
|12,500
|0.625
|Increases as temperature rises up to 240
|Increases as temperature rises up to 60
|166.7%
|===

=== Steam only
In Steam Mode the Reactor using its internal heat to convert water into Compressed Steam to use in the Super HV Turbine

====Reactor Stats

The reactor clock set to 150% will maintain the current heat level inside the reactor the fuel usage will be stable at this clock setting

|===
| |Water |coolant |Compressed Steam

|heat @ 25%
|170
|38
|145

|heat @ 50%
|200
|48
|165

|heat @ 75%
|218
|57
|180

|heat @ 100%
|237
|60
|196
|===

[Note]
====
These are very close values taken at the around start of the cycle, and will vary due to being heat dependant and the fluctuations in the reactors internal heat.
====

=== Power and Steam

In Dual output mode, you decrease the production in Single output mode to split the energy from the cores to be able to output both compressed steam and power from a single reactor ring.

> TODO: Add Dual output mode Stats